apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  selector:
    matchLabels:
      app: comment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: server
          env:
            - name: DB_SERVER
              value: localhost:3306
            - name: DB_NAME
              value: course_project
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: ""
            - name: PLUGIN_SERVICE_URL
              value: http://localhost:8083
            - name: IDENTITY_SERVICE_URL
              value: http://localhost:8082
          image: danikvitek/comment-service
          ports:
            - name: http
              containerPort: 8081

---